modLoader = "javafml"
loaderVersion = "[51,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "forcegl20"
version = "${version}"
displayName = "ForceGL20"
authors = "KabanFriends, Coredex(coredex-source)"
description = "Forces the game to use OpenGL 2.0!"
logoFile = "assets/forcegl20/icon.png"

[[dependencies.forcegl20]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.forcegl20]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"
