modLoader = "javafml"  # Verify if this should remain 'javafml' or change for NeoForge
loaderVersion = "[2,)"  # Adjust to the correct NeoForge version
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "forcegl20"
version = "${version}"
displayName = "ForceGL20"
authors = "KabanFriends, Coredex(coredex-source)"
description = "Forces the game to use OpenGL 2.0!"
logoFile = "assets/forcegl20/icon.png"

[[dependencies.forcegl20]]
modId = "neoforge"
type="required"
versionRange = "[21.1.40,)"  # Ensure this matches your NeoForge version
ordering = "NONE"
side = "CLIENT"

[[dependencies.forcegl20]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1]"  # Ensure the version range covers supported versions
ordering = "NONE"
side = "CLIENT"
